version: 0.2
env:
  variables:
    APP_NAME: "angular-cicd-pipeline-demo"
phases:
  install:
    runtime-versions:
      nodejs: 16.x
    commands:
      - echo install process started
      - echo "Hello World"
  build:
    commands:
      - echo build process started now
      - cd ../../
      - ls ../*
  post_build:
    commands:
      - echo build process finished, we should uplload to S3 now
      - cd ../
      - ls -la
      - echo "aws s3 sync . s3://app-culturi --delete"
